[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  version = "^0.14.0"
  name = "github.com/tendermint/go-amino"

[[constraint]]
  revision = "5a6822c8acbd7353729cbb5d8393de2f6da39425"
  name = "github.com/tendermint/tendermint"

[prune]
  go-tests = true
  unused-packages = true
