[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  version = "^0.14.0"
  name = "github.com/tendermint/go-amino"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  revision = "daddebac29d9f1258f7e93282e84709bd16a0acd"

[prune]
  go-tests = true
  unused-packages = true
