[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  version = "^0.14.0"
  name = "github.com/tendermint/go-amino"

[[constraint]]
  name = "github.com/danil-lashin/tendermint"
  revision = "4f244ca48cb089f0ea0c88dc608c525281513435"

[prune]
  go-tests = true
  unused-packages = true
