[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  version = "=0.12.0"
  name = "github.com/tendermint/go-amino"

[[constraint]]
  version = "=0.24.0"
  name = "github.com/tendermint/tendermint"

[prune]
  go-tests = true
  unused-packages = true
