[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  version = "^0.14.0"
  name = "github.com/tendermint/go-amino"

[[constraint]]
  name = "github.com/danil-lashin/tendermint"
  revision = "7f73a6464cd3a374924e709e26f860787266982b"

[prune]
  go-tests = true
  unused-packages = true
